parameters:
#    zdc_user.example.class: Zdc\UserBundle\Example

services:
#    zdc_user.example:
#        class: %zdc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
